spring:
  #  datasource:
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    url: jdbc:mysql:///vueblog2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  #    username: root
  #    password: root
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


mybatis:
  config-location: classpath:/mybatis-config.xml

server:
  port: 8084

logging:
  #  config: classpath:config/logback.xml
  level:
    org:
      springframework:
        security: info

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


