spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql:///vueblog2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  redis:
#    host: 39.105.106.135
#    port: 6379
#    password: 123456789PP
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  elasticsearch:
    rest:
      uris: http://140.210.209.238:9200  #此处配置elasticsearch的访问地址

mybatis:
  config-location: classpath:mybatis-config.xml


server:
  port: 8082

logging:
#  config: classpath:config/logback.xml
  level:
    org:
      springframework:
        security: info

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true



#auth:
#  ttl: 3600000  #token过期时间
#  clientId: dongyimai  #客户端账号
#  clientSecret: 123 #客户端密码
#  cookieDomain: localhost #cookie域名
#  cookieMaxAge: -1     #cookie有效期


# hystrix:
#   # 启用fegin断路器
#   enabled: true
