spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///vueblog2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  config-location: classpath:/mybatis-config.xml


server:
  port: 8081

logging:
#  config: classpath:config/logback.xml
  level:
    org:
      springframework:
        security: info

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml

auth:
  ttl: 3600000  #token过期时间
  clientId: dongyimai  #客户端账号
  clientSecret: 123 #客户端密码
  cookieDomain: localhost #cookie域名
  cookieMaxAge: -1     #cookie有效期
